import en from "./demo-custodian.en.json";
import vi from "./demo-custodian.vi.json";
import type { Messages } from "../locale";

/** `demo-custodian.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoCustodian: Messages<typeof en> = { en, vi: vi satisfies typeof en };
