import en from "./demo-maker.en.json";
import vi from "./demo-maker.vi.json";
import type { Messages } from "../locale";

/** `demo-maker.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoMaker: Messages<typeof en> = { en, vi: vi satisfies typeof en };
