import en from "./demo-brand.en.json";
import vi from "./demo-brand.vi.json";
import type { Messages } from "../locale";

/** `demo-brand.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoBrand: Messages<typeof en> = { en, vi: vi satisfies typeof en };
