import en from "./demo-manufacturer.en.json";
import vi from "./demo-manufacturer.vi.json";
import type { Messages } from "../locale";

/** `demo-manufacturer.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoManufacturer: Messages<typeof en> = { en, vi: vi satisfies typeof en };
