import en from "./demo-common.en.json";
import vi from "./demo-common.vi.json";
import type { Messages } from "../locale";

/** `demo-common.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoCommon: Messages<typeof en> = { en, vi: vi satisfies typeof en };
