import en from "./demo-shell.en.json";
import vi from "./demo-shell.vi.json";
import type { Messages } from "../locale";

/** `demo-shell.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoShell: Messages<typeof en> = { en, vi: vi satisfies typeof en };
