import en from "./demo-admin.en.json";
import vi from "./demo-admin.vi.json";
import type { Messages } from "../locale";

/** `demo-admin.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const demoAdmin: Messages<typeof en> = { en, vi: vi satisfies typeof en };
