import en from "./landing.en.json";
import vi from "./landing.vi.json";
import type { Messages } from "../locale";

/** `landing.vi.json` is generated by `scripts/i18n-translate.ts`; edit English only. */
export const landing: Messages<typeof en> = { en, vi: vi satisfies typeof en };
