/**
 * Domain vocabulary per language. English is `domain.ts` itself; Vietnamese is
 * generated by the translation pipeline from `demo-labels.en.json`, which
 * `scripts/i18n-extract-labels.ts` copies out of `domain.ts`.
 *
 * A label added to `domain.ts` without re-running extract + translate fails the
 * type check here, because the Vietnamese file no longer has every key.
 */

import vi from "@/lib/i18n/messages/demo-labels.vi.json";
import type { Locale } from "@/lib/i18n/locale";
import * as domain from "./domain";

const EN = {
  ACTION_KIND_LABELS: domain.ACTION_KIND_LABELS,
  ARRIVAL_ISSUE_LABELS: domain.ARRIVAL_ISSUE_LABELS,
  ASSURANCE_LABELS: domain.ASSURANCE_LABELS,
  BUCKET_LABELS: domain.BUCKET_LABELS,
  DATA_SOURCE_LABELS: domain.DATA_SOURCE_LABELS,
  FACILITY_TYPE_LABELS: domain.FACILITY_TYPE_LABELS,
  FORMAT_LABELS: domain.FORMAT_LABELS,
  INPUT_TYPE_LABELS: domain.INPUT_TYPE_LABELS,
  MATERIAL_CATEGORY_LABELS: domain.MATERIAL_CATEGORY_LABELS,
  MILESTONE_LABELS: domain.MILESTONE_LABELS,
  MOVEMENT_REASON_LABELS: domain.MOVEMENT_REASON_LABELS,
  ORG_ROLE_DESCRIPTIONS: domain.ORG_ROLE_DESCRIPTIONS,
  ORG_ROLE_LABELS: domain.ORG_ROLE_LABELS,
  ORGANISATION_TYPE_LABELS: domain.ORGANISATION_TYPE_LABELS,
  PRODUCT_CATEGORY_LABELS: domain.PRODUCT_CATEGORY_LABELS,
  QUALITY_CLASS_LABELS: domain.QUALITY_CLASS_LABELS,
  ROLE_DESCRIPTIONS: domain.ROLE_DESCRIPTIONS,
  ROLE_LABELS: domain.ROLE_LABELS,
  SOURCING_CATEGORY_LABELS: domain.SOURCING_CATEGORY_LABELS,
  STATUS_LABELS: domain.STATUS_LABELS,
  SUITABILITY_LABELS: domain.SUITABILITY_LABELS,
  TIME_ACTIVITY_LABELS: domain.TIME_ACTIVITY_LABELS,
  UNIT_LABELS: domain.UNIT_LABELS,
};

export type DomainLabels = typeof EN;

const VI: DomainLabels = vi;

export function labelsFor(locale: Locale): DomainLabels {
  return locale === "vi" ? VI : EN;
}

/** Same fallback as `domain.statusLabel`, in the given language. */
export function statusLabelIn(labels: DomainLabels, status: string): string {
  return labels.STATUS_LABELS[status] ?? status.replace(/_/g, " ");
}
